vendor implementation and log file
ampp8800/pizzeria pull request #7
Opened 2021-11-08 23:19 UTC by ampp8800

2021-11-09 08:20 UTC, EitherNor requested changes

2021-11-09 08:20 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/OrderManager.java
> +                order.setDate(new Date(new Date().getTime() - order.getDate().getTime()));
Зачем это?

2021-11-09 08:20 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Pizzeria.java
> +            supplier.join();
Зачем тебе ждать окончания потока поставщика? У нас окончание работы пиццерии определяется по условию выполнения всех заказов

2021-11-09 08:20 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Supplier.java
> +        while ((Utils.getNumberOfOrderGenerators() != 0) || (OrderQueueWrapper.getInstance().getQueueOrder().peekFirst() != null)) {
По твоей логике у тебя поставщик сдыхает раньше, чем повара приготовляют последние заказы и статистика по итогу выводится раньше, чем нужно. Лучше не завязывай вывод статистики на работу поставщика вообще, а на конец работы всех поваров

2021-11-09 08:20 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Supplier.java
> +                warehouse.setIngredientsInStock(ingredientsInStock);
Этот же метод вызывается в OrderManager в pickUpIngredientsFromWarehouse. Представь, что там это сработает на миллисекунду позже, чем твой поставщик пополнил запасы. В итоге у тебя в складе будет то состояние ингредиентов, которое orderManager взял из него за вычетом количества на какой-то заказ. Подумай, как избежать этого.

2021-11-09 08:20 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Supplier.java
> +                warehouse.setIngredientsInStock(ingredientsInStock);
Нужно сделать централизованное изменение склада, т.е. в одном месте. На стороне самого склада и сделать это так, чтобы OrderManager мог только уменьшать количество когда взял нужные ингредиенты для заказа, а не пушить туда целиком всё состояние склада, точно так же и поставщик должен только прибавлять ингредиенты, а не пушить весь склад. 
Иначе у тебя в один момент времени возникают 2 разных состояния склада в разных классах, которое ты потом пушишь на склад, а должно быть такое состояние одно и все его изменения должны быть синхронизированы

2021-11-09 17:53 UTC, ampp8800 commented on src/main/java/com/ampp8800/pizzeria/OrderManager.java
> +                order.setDate(new Date(new Date().getTime() - order.getDate().getTime()));
тут я храню сколько времени прошло от появления заказа до его исполнения, да, в Date не очень правильно, наверное доработать класс Order стоит (скажи "да, стоит")

2021-11-09 20:33 UTC, ampp8800 commented on src/main/java/com/ampp8800/pizzeria/Supplier.java
> +        while ((Utils.getNumberOfOrderGenerators() != 0) || (OrderQueueWrapper.getInstance().getQueueOrder().peekFirst() != null)) {
тут все ок, сначала повар забирает ингредиенты со склада, затем удаляет заказ из очереди => поставщик "умрет" после последних взаимодействий со складом, мб не по правилам ООП, если так- то переделаю

2021-11-10 15:31 UTC, EitherNor requested changes

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Order.java
> +    private int timeInQueue;
Или добавь единицу измерения в название поля или поменяй тип на лонг и храни миллисекунды, а в секунды переводи непосредственно в выводе статистики

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Pizzeria.java
> +        ArrayList<Cook> cooks = new ArrayList<>();
Тип ссылки должен быть максимально абстрактным - List

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Utils.java
> +    private static int numberOfCooks = 0;
AtomicInteger если не делаешь методы доступа синхронизированными

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Utils.java
>      private static int numberOfOrderGenerators = 0;
AtomicInteger если не делаешь методы доступа синхронизированными

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Utils.java
> +    public static void addNumberOfCooks() {
incrementNumberOfCooks

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Utils.java
> +    public static void numberOfCooksCompleted() {
decrementNumberOfCooks

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Utils.java
>      public static void addedOrderGenerator() {
incrementNumberOfOrderGenerators

2021-11-10 15:31 UTC, EitherNor commented on src/main/java/com/ampp8800/pizzeria/Utils.java
>      public static void generationOfOrdersCompleted() {
decrementNumberOfOrderGenerators

2021-11-11 08:49 UTC, merged